MODEL:
  META_ARCHITECTURE: "single_sfda_RCNN"
  WEIGHT: "/home/diml/kaist_dataset/irg-sfda/checkpoint/cityscapes_baseline/model_final.pth"
  MASK_ON: False
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    NUM_CLASSES: 8
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
TEST:
  EVAL_PERIOD: 500
DATASETS:
  TRAIN: ("cityscape_2007_train_t",)
  TEST: ("cityscape_2007_test_t",)
SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 40000
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./checkpoint/foggy_singlesfda"
SOURCE_FREE:
  TYPE: True
  MODE: True

