MODEL:
  META_ARCHITECTURE: "student_sfda_RCNN_jy"
  WEIGHT: "/home/diml/kaist_dataset/irg-sfda/checkpoint/cityscapes_baseline/model_final.pth"
  MASK_ON: False
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    NUM_CLASSES: 8
  RESNETS:
    NORM: "FrozenBN" 
    OUT_FEATURES: ["res4"]
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATASETS:
  TRAIN: ("cityscape_2007_train_t",)
  TEST: ("cityscape_2007_test_t",)
  # TRAIN: ("cityscape_car_2007_train_s",)
  # TEST: ("cityscape_car_2007_test_s",)
  # TRAIN: ("clipart_train",)
  # TEST: ("clipart_test",)
  # TRAIN: ("watercolor_train",)
  # TEST: ("watercolor_test",)

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: ()
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 0
SOURCE_FREE:
  TYPE: True
  MODE: True
OUTPUT_DIR: "./checkpoint/foggy_layerwise"

